export enum Field {
  PRODUCT_NAME = 'PRODUCT_NAME',
  PRODUCT_REF = 'PRODUCT_REF',
  PRODUCT_LOT = 'PRODUCT_LOT',
  PRODUCT_MANUFACTURER = 'PRODUCT_MANUFACTURER',
  PRODUCT_PURCHASE_DATE = 'PRODUCT_PURCHASE_DATE',
  PRODUCT_SERIES_CODE = 'PRODUCT_SERIES_CODE',
  ID = 'ID',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  USERNAME = 'USERNAME',
  EMAIL = 'EMAIL',
  STATUS = 'STATUS',
  LOCKED = 'LOCKED'
}
